/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/desk-model-2.glb -o app/components/scene/DeskAndLaptopModel.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube001_3: THREE.Mesh
    Cube001_4: THREE.Mesh
    Cube001_5: THREE.Mesh
    Cube001_6: THREE.Mesh
    Cube001_7: THREE.Mesh
    Cube001_8: THREE.Mesh
    Cube001_9: THREE.Mesh
    Text: THREE.Mesh
    Cube004_1: THREE.Mesh
    Cube004_2: THREE.Mesh
    Cube004_3: THREE.Mesh
    Cube002: THREE.Mesh
    Cube013_1: THREE.Mesh
    Cube013_2: THREE.Mesh
    Cube013_3: THREE.Mesh
    Cube004: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Cube015_1: THREE.Mesh
  }
  materials: {
    Metal: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    body: THREE.MeshStandardMaterial
    ['black.002']: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    dark: THREE.MeshStandardMaterial
    ['glass.002']: THREE.MeshPhysicalMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshPhysicalMaterial
    ['glass.003']: THREE.MeshPhysicalMaterial
    ['Apple-logo']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    Dark: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    key: THREE.MeshStandardMaterial
    ['key.002']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['black.003']: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    ['black.001']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/desk-model-2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.015, -0.093, -0.035]} scale={0.269}>
        <group position={[-0.029, -0.016, 0.02]} scale={3.72}>
          <mesh geometry={nodes.Cube005.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Cube005_1.geometry} material={materials.Wood} />
        </group>
      </group>
      <group position={[-0.015, 0.619, -0.004]} scale={0.52}>
        <group position={[0, 0.027, -0.28]} rotation={[-0.263, 0, 0]} scale={0.259}>
          <group position={[0.001, -0.051, -0.002]} rotation={[1.572, 0, 0]} scale={1.06}>
            <mesh geometry={nodes.Cube001_1.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube001_2.geometry} material={materials['black.002']} />
            <mesh geometry={nodes.Cube001_3.geometry} material={materials.screen} />
            <mesh geometry={nodes.Cube001_4.geometry} material={materials.dark} />
            <mesh geometry={nodes.Cube001_5.geometry} material={materials['glass.002']} />
            <mesh geometry={nodes.Cube001_6.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube001_7.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cube001_8.geometry} material={materials['glass.003']} />
            <mesh geometry={nodes.Cube001_9.geometry} material={materials['Apple-logo']} />
          </group>
          <mesh geometry={nodes.Text.geometry} material={materials['Material.003']} position={[0.01, 0.064, -0.002]} rotation={[1.571, 0, 0]} scale={[0.044, 0.045, 0.049]} />
        </group>
        <group position={[0, 0.017, -0.003]} rotation={[-0.016, 0, 0]} scale={0.274}>
          <mesh geometry={nodes.Cube004_1.geometry} material={materials.body} />
          <mesh geometry={nodes.Cube004_2.geometry} material={materials.Dark} />
          <mesh geometry={nodes.Cube004_3.geometry} material={materials['Material.005']} />
        </group>
        <mesh geometry={nodes.Cube002.geometry} material={materials.body} position={[0, 0.025, 0.149]} rotation={[0.001, 0, 0]} scale={0.121} />
        <group position={[0.006, 0.027, -0.093]} scale={0.259}>
          <mesh geometry={nodes.Cube013_1.geometry} material={materials.key} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials['key.002']} />
          <mesh geometry={nodes.Cube013_3.geometry} material={materials['Material.006']} />
        </group>
        <mesh geometry={nodes.Cube004.geometry} material={materials['black.003']} position={[-0.393, 0.019, -0.222]} rotation={[0.001, 0, 0]} scale={[0.006, 0.004, 0.008]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials.black} position={[-0.392, 0.02, -0.227]} rotation={[0.001, 0, 0]} scale={[0.006, 0.003, 0.001]} />
        <mesh geometry={nodes.Cube007.geometry} material={materials.black} position={[-0.392, 0.018, -0.227]} rotation={[0.001, 0, 0]} scale={[0.006, 0.003, 0.001]} />
        <mesh geometry={nodes.Cube008.geometry} material={materials['black.003']} position={[-0.393, 0.019, -0.183]} rotation={[0.001, 0, 0]} scale={[0.006, 0.004, 0.008]} />
        <mesh geometry={nodes.Cube009.geometry} material={materials.black} position={[-0.392, 0.02, -0.188]} rotation={[0.001, 0, 0]} scale={[0.006, 0.003, 0.001]} />
        <mesh geometry={nodes.Cube010.geometry} material={materials.black} position={[-0.392, 0.018, -0.188]} rotation={[0.001, 0, 0]} scale={[0.006, 0.003, 0.001]} />
        <mesh geometry={nodes.Cube011.geometry} material={materials.key} position={[0.14, 0.027, -0.167]} scale={0.259} />
        <mesh geometry={nodes.Cube013.geometry} material={materials.body} position={[-0.4, 0.026, -0.213]} scale={[0.001, 0, 0.001]} />
        <group position={[0.321, 0.026, -0.213]} scale={[0.001, 0, 0.001]}>
          <mesh geometry={nodes.Cube015.geometry} material={materials.body} />
          <mesh geometry={nodes.Cube015_1.geometry} material={materials['black.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/desk-model-2.glb')
