/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/desk-model-optimized.glb -o app/components/scene/DeskAndLaptopModel.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube004_1: THREE.Mesh
    Cube004_2: THREE.Mesh
    Cube004_3: THREE.Mesh
    Cube013: THREE.Mesh
    Cube013_1: THREE.Mesh
    Cube004: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube001_3: THREE.Mesh
    Cube001_4: THREE.Mesh
    Cube001_5: THREE.Mesh
  }
  materials: {
    Metal: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['key.002']: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshPhysicalMaterial
    ['Apple-logo']: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshPhysicalMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/desk-model-optimized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.023, -0.097, -0.029]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Wood} />
      </group>
      <group position={[-0.015, 0.628, -0.006]} rotation={[-0.016, 0, 0]} scale={0.143}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials.PaletteMaterial003} />
      </group>
      <group position={[-0.012, 0.633, -0.053]} scale={0.135}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['key.002']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.PaletteMaterial004} />
      </group>
      <mesh geometry={nodes.Cube004.geometry} material={materials.PaletteMaterial005} position={[-0.22, 0.629, -0.12]} rotation={[0.001, 0, 0]} scale={[0.003, 0.002, 0.004]} />
      <group position={[-0.015, 0.626, -0.149]} rotation={[1.309, 0, 0]} scale={0.143}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.screen} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.PaletteMaterial006} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.PaletteMaterial008} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials['Apple-logo']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials.PaletteMaterial007} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/desk-model-optimized.glb')
